package com.masteringselenium.locatorsWebElement;

import com.masteringselenium.DriverFactory;
import com.masteringselenium.locatorsWebElement.factories.MercuryHPFactory;
import com.masteringselenium.locatorsWebElement.factories.MercuryReservationFactory;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.Test;

import java.util.logging.Logger;

import static org.testng.Assert.assertTrue;

/**
 * Package: com.masteringselenium.locators
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 13.01.2019 2019
 */
public class MercuryResevationWD extends DriverFactory {
    private Logger  LOGGER = Logger.getLogger(this.getClass().getName());
    WebDriver driver;



    @Test
    public void MerucyReservationCheck() throws Exception {
        driver = DriverFactory.getDriver();
        driver.navigate().to("http://newtours.demoaut.com/");
        MercuryHPFactory mercuryHPFactory = new MercuryHPFactory();
        mercuryHPFactory.login();
        MercuryReservationFactory mercuryReservationFactory = new MercuryReservationFactory();
        //Test
        assertTrue(mercuryReservationFactory.flightFinderDisplayed());
        assertTrue(mercuryReservationFactory.oneWaySelected());

       assertTrue(WindowsUtils.thisIsWindows());
        }
    }

