package com.masteringselenium.selenide;

import org.openqa.selenium.By;
import org.testng.annotations.Test;

import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.open;

/**
 * Package: com.masteringselenium.selenide
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 18.01.2019 2019
 */
public class GoogleTestWD {
    @Test
    public void search_selenide_google() throws InterruptedException {
        open("http://google.com");
        $(By.name("q")).val("selenide").pressEnter();
    }
}
