package com.masteringselenium.selenide;

import com.codeborne.selenide.*;
import com.masteringselenium.DriverFactory;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import static com.codeborne.selenide.CollectionCondition.size;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.*;

/**
 * Package: com.masteringselenium.selenide Generated by: Hoang.Son.Nguyen Generated at: 21.01.2019
 * 2019 https://www.seleniumeasy.com/test/
 */
public class SelenideBasicsWKD extends DriverFactory{
  @BeforeTest
  public void setUp() throws Exception {
    WebDriverRunner.setWebDriver(DriverFactory.getDriver());
    open("https://www.seleniumeasy.com/test/");
  }

  @Test
  public void testSeleniumBasics() throws InterruptedException {
    // cssSelector by ID
    WebElement slogan = $("#site-slogan").shouldBe(Condition.visible);
    // $$ response a Collection
    $$(By.xpath("//div")).shouldHave(size(63));
    $$(By.xpath("//div")).filter(Condition.visible).shouldHave(size(39));
    System.out.println("Anzahl: " + $$(By.xpath("//div")).filter(Condition.visible).size());
    // findBy full text
    $(byText("Make Yourself an Expert")).shouldBe(Condition.visible);
    // find by partial text
    $(withText("an expert will be fun"))
        .shouldHave(text("Becoming an expert will be fun and exciting."));
    // find parent
    $(By.xpath("//img[@class='cbt']"))
        .parent()
        .parent()
        .shouldHave(attribute("class", "top-banner col-md-6"));
    // find child
    $(By.xpath("//div[@class='top-banner col-md-6']"))
        .find(
            By.xpath(
                "//a[@href='https://crossbrowsertesting.com/?utm_source=seleniumeasy&utm_medium=da&utm_campaign=sedemo']"))
        .shouldBe(visible);
     SelenideElement a = $(byXpath("//i[@class='fa fa-angle-right']")).shouldBe(visible);
  }
}
