package com.masteringselenium.selenide.factories;

import com.codeborne.selenide.WebDriverRunner;
import com.masteringselenium.DriverFactory;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import static com.codeborne.selenide.Selenide.open;

/**
 * Package: com.masteringselenium.selenide.factories Generated by: Hoang.Son.Nguyen Generated at:
 * 23.01.2019 2019
 */
public class SelenideEasy extends DriverFactory {

  @BeforeTest
  public void setUp() throws Exception {
    WebDriverRunner.setWebDriver(DriverFactory.getDriver());
    open("https://www.seleniumeasy.com/test/");
  }

  @Test
  public void testSelenEasy() {
    SelenideEasyFactory selenideEasyFactory = new SelenideEasyFactory();
    selenideEasyFactory.logoVisible();
    selenideEasyFactory.allExamplesClose();
  }
}
