package com.masteringselenium.selenide.factories;

import com.codeborne.selenide.Condition;
import com.codeborne.selenide.Selenide;
import com.codeborne.selenide.SelenideElement;

import static com.codeborne.selenide.Selectors.byXpath;
import static com.codeborne.selenide.Selenide.$;

/**
 * Package: com.masteringselenium.selenide.factories Generated by: Hoang.Son.Nguyen Generated at:
 * 23.01.2019 2019
 */
public class SelenideEasyFactory {
  SelenideElement inputForm =
      $(byXpath("//li[@class='tree-branch']//a[@href='#'][contains(text(),'Input Forms')]"))
          .shouldBe(Condition.visible);
  SelenideElement allExamples =
      $(byXpath("//a[contains(text(),'All Examples')]")).shouldBe(Condition.visible);

  public void logoVisible() {
    SelenideElement logo =
        $(byXpath("//a[contains(text(),'Selenium Easy')]")).shouldBe(Condition.visible);
  }
  public void allExamplesClose(){
      allExamples.click();
      inputForm.shouldNotBe(Condition.visible);
  }

}
