package com.masteringselenium.listenersScreenshot;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.Augmenter;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Logger;

import static com.masteringselenium.DriverFactory.getDriver;

/**
 * Package: com.masteringselenium.listeners Generated by: Hoang.Son.Nguyen Generated at: 02.01.2019
 * 2019
 */
public class ScreenshotListener extends TestListenerAdapter {
  Logger LOGGER = Logger.getLogger("Error screen shot: ");
  private boolean createFile(File screenshot) throws IOException {
    boolean fileCreated = false;
    if (screenshot.exists()) {
      fileCreated = true;
    } else {
      File parentDirectory = new File(screenshot.getParent());
      if (parentDirectory.exists() || parentDirectory.mkdir()) {
        fileCreated = screenshot.createNewFile();
      }
    }
    return fileCreated;
  }

  private void writeScreenshotToFile(WebDriver driver, File screenshot) throws IOException {
    FileOutputStream screenshotStream = new FileOutputStream(screenshot);
    screenshotStream.write(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES));
    screenshotStream.close();
  }

  @Override
  public void onTestFailure(ITestResult faillingTest) {
    try {
      WebDriver driver = getDriver();
      String screenshotDirectory = System.getProperty("screenshotDirectory");
      String screenshotAbsolutePath =
          screenshotDirectory
              + File.separator
              + System.currentTimeMillis()
              + "_"
              + faillingTest.getName()
              + ".png";
        File screenshot = new File(screenshotAbsolutePath);
        if (createFile(screenshot)) {
        try {
          writeScreenshotToFile(driver, screenshot);
        } catch (ClassCastException weNeedToAugmentOurDriverObject) {
          writeScreenshotToFile(new Augmenter().augment(driver), screenshot);
        }
        LOGGER.warning("Written screenshot to " + screenshotAbsolutePath);
      } else {
          LOGGER.warning("Unable to create " + screenshotAbsolutePath);
      }

    } catch (Exception ex) {
      LOGGER.warning("Unable to capture screenshot...");
      ex.printStackTrace();
    }
  }
}
