package com.masteringselenium.ObjectMap;

import org.openqa.selenium.By;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Logger;

/**
 * Package: com.masteringselenium.ObjectMap Generated by: Hoang.Son.Nguyen Generated at: 18.01.2019
 * 2019
 */
public class ObjectMap {
  Properties properties;
  private Logger LOOGER = Logger.getLogger(this.getClass().getName());

  public ObjectMap(String mapFile) {
    properties = new Properties();
    try {
      FileInputStream in = new FileInputStream(mapFile);
      properties.load(in);
    } catch (IOException e) {
      LOOGER.warning(e.getMessage());
    }
  }

  public By getLocator(String logicalElementName) throws Exception {
    // read value using logical name al Key
    String locator = properties.getProperty(logicalElementName);

    // split the value wich contains locator type and value
    String locatorType = locator.split(">")[0];
    String locatorValue = locator.split(">")[1];

    switch (locatorType.toLowerCase()) {
      case "id":
        return By.id(locatorValue);
      case "name":
        return By.name(locatorValue);
      case "class":
        return By.className(locatorValue);
      case "classname":
        return By.className(locatorValue);
      case "tag":
        return By.tagName(locatorValue);
      case "tagname":
        return By.tagName(locatorValue);
      case "link":
        return By.linkText(locatorValue);
      case "linktext":
        return By.linkText(locatorValue);
      case "cssselector":
        return By.cssSelector(locatorValue);
      case "xpath":
        return By.xpath(locatorValue);
      case "partiallinktext":
        return By.partialLinkText(locatorValue);
      default:
        throw new Exception("Locator type '" + locatorType + "' not defined!!");
    }
  }
}
