package com.masteringselenium.html5Videos;

import com.masteringselenium.DriverFactory;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.testng.annotations.Test;

import java.io.File;
import java.util.concurrent.TimeUnit;

import static org.testng.Assert.assertTrue;

/**
 * Package: com.masteringselenium.html5Videos Generated by: Hoang.Son.Nguyen Generated at:
 * 19.01.2019 2019
 */
public class testHTML5VideoWD extends DriverFactory {
  @Test
  public void testHtml5Video() throws Exception {
    File scrFile = null;
    WebDriver driver = DriverFactory.getDriver();
    driver.navigate().to("https://www.youtube.com/watch?v=vOmeeK_7mq8&t=172s");
    driver.manage().timeouts().pageLoadTimeout(15, TimeUnit.SECONDS);
    WebElement videoPlayer =
        driver.findElement(By.xpath("//video[@class='video-stream html5-main-video']"));
    JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
    String source =
        (String) jsExecutor.executeScript("return arguments[0].currentSrc;", videoPlayer);
    // Get the Duration of Video
    double duration =
        (double) jsExecutor.executeScript("return arguments[0].duration", videoPlayer);
    assertTrue(source.contains("https://www.youtube.com/"));
      assertTrue(Double.toString(duration).contains("246"));
  }
}
