package com.masteringselenium.locators;

import com.masteringselenium.DriverFactory;
import com.masteringselenium.locators.factories.MercuryHPFactory;
import com.masteringselenium.locators.factories.MercuryReservationFactory;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.logging.Logger;

import static org.testng.Assert.assertTrue;

/**
 * Package: com.masteringselenium.locators
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 13.01.2019 2019
 */
public class MercuryResevationWD extends DriverFactory {
    private Logger LOGGER;
    MercuryReservationFactory mercuryReservationFactory;
    WebDriver driver;

    @BeforeMethod
    public void setUp() throws Exception {
        LOGGER = Logger.getLogger(this.getClass().getName());
        driver = DriverFactory.getDriver();
    }

    @Test
    public void MerucyReservationCheck() throws Exception {
        driver.navigate().to("http://newtours.demoaut.com/");
        MercuryHPFactory mercuryHPFactory = new MercuryHPFactory();
        mercuryHPFactory.login();
        mercuryReservationFactory = new MercuryReservationFactory();
        //Test
        assertTrue(mercuryReservationFactory.flightFinderDisplayed());
        assertTrue(mercuryReservationFactory.oneWaySelected());

        assertTrue(WindowsUtils.thisIsWindows());
        }
    }

