package com.masteringselenium.checkDownloadLinks;

/**
 * Package: com.masteringselenium.checkDownloadLinks Generated by: Hoang.Son.Nguyen Generated at:
 * 04.01.2019 2019
 * It's actually pretty simple to check links.
 * All you need to do is find the link on the page,
 * extract a URL from its href  attribute,
 * and then check to see if sending an
 * HTTP GET request to that URL results in a valid response.
 */
import org.apache.http.client.methods.*;

public enum RequestType {
  OPTIONS(new HttpOptions()),
  GET(new HttpGet()),
  HEAD(new HttpHead()),
  PATCH(new HttpPatch()),
  POST(new HttpPost()),
  PUT(new HttpPut()),
  DELETE(new HttpDelete()),
  TRACE(new HttpTrace());
  private final HttpRequestBase requestMethod;

  RequestType(HttpRequestBase requestMethod) {
    this.requestMethod = requestMethod;
  }

  public HttpRequestBase getRequestMethod() {
    return this.requestMethod;
  }
}
