package com.masteringselenium.locators.factories;

import com.masteringselenium.DriverFactory;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.CacheLookup;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.openqa.selenium.support.PageFactory;

import java.util.List;

/**
 * Package: com.masteringselenium.locators.factories Generated by: Hoang.Son.Nguyen Generated at:
 * 08.01.2019 2019
 */
public class MecuryHPFactory {
  public MecuryHPFactory() throws Exception {
    PageFactory.initElements(DriverFactory.getDriver(), this);
  }

  @CacheLookup
  @FindBy(how = How.TAG_NAME, using = "a")
  List<WebElement> byTagName;

  public int countByTagName() {
    return byTagName.size();
  }

  @CacheLookup
  @FindBy(how = How.XPATH, using = "//input[@name='password']")
  WebElement pwd;

  public boolean pwdSisplaed() {
    return pwd.isDisplayed();
  }

  @CacheLookup
  @FindBy(
      how = How.CSS,
      using =
          "tbody:nth-child(1) tr:nth-child(1) td:nth-child(1) p:nth-child(1) > img:nth-child(1)")
  WebElement logo;
  public boolean logoDisplayed() {
    return logo.isDisplayed();
  }

  @CacheLookup
  @FindBy(how = How.CSS, using = ".mouseOut")
  List<WebElement> mouseOut;
  public int mouseOutSize() {
    for(WebElement e : mouseOut){
      System.out.println(e.getAttribute("onmouseout"));
    }
    return mouseOut.size();
  }
}
