package com.masteringselenium.locators.factories;

import com.masteringselenium.DriverFactory;
import com.masteringselenium.locators.WindowsUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.CacheLookup;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import javax.xml.xpath.XPath;
import java.util.concurrent.TimeUnit;

/**
 * Package: com.masteringselenium.locators.factories Generated by: Hoang.Son.Nguyen Generated at:
 * 13.01.2019 2019
 */
public class MercuryReservationFactory {
  WebDriver driver;

  public MercuryReservationFactory() throws Exception {
    // WindowsUtils.killByName("firefox.exe");  // close open FF windows
    driver = DriverFactory.getDriver();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    PageFactory.initElements(driver, this);
  }

  @CacheLookup
  @FindBy(xpath = "//img[@src=\'/images/masts/mast_flightfinder.gif\']")
  private WebElement flightFinder;

  public boolean flightFinderDisplayed() {
    return new WebDriverWait(driver, 30)
        .until(ExpectedConditions.visibilityOf((flightFinder)))
        .isDisplayed();
  }

  @CacheLookup
  @FindBy(xpath = "//input[@value='oneway']")
  private WebElement oneWay;

  public boolean oneWaySelected() {
    if (!oneWay.isSelected()) {
      oneWay.click();
    }
    return oneWay.isSelected();
  }


}
