package com.masteringselenium.effectivePageObjects;

import com.masteringselenium.DriverFactory;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.CacheLookup;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.openqa.selenium.support.PageFactory;

/**
 * Package: com.masteringselenium.effectivePageObjects
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 03.01.2019 2019
 */
public class LoggedPageFactory {
    LoggedPageFactory() throws Exception {
        PageFactory.initElements(DriverFactory.getDriver(),this);
    }

    @CacheLookup
    @FindBy(how = How.XPATH, using = "//a[@title='Log me out']")
    private WebElement logOutBtn;

    public boolean logOutVisible(){
        return logOutBtn.isEnabled();
    }
}
