package com.masteringselenium.effectivePageObjects;

import com.masteringselenium.DriverFactory;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.CacheLookup;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 * Package: com.masteringselenium.effectivePageObjects Generated by: Hoang.Son.Nguyen Generated at:
 * 03.01.2019 2019
 */
public class LoggedPageFactory {
  LoggedPageFactory() throws Exception {
    PageFactory.initElements(DriverFactory.getDriver(), this);
  }

  @CacheLookup
  @FindBy(how = How.XPATH, using = "//a[@title='Log me out']")
  private WebElement logOutBtn;

  @CacheLookup
  @FindBy(how = How.XPATH, using = "//a[@title='Women']")
  private WebElement women;

  @CacheLookup
  @FindBy(how = How.XPATH, using = "//img[@title='Faded Short Sleeve T-shirts']")
  private WebElement tShirt;

  @CacheLookup
  @FindBy(
      how = How.XPATH,
      using =
          "//li[@class='ajax_block_product col-xs-12 col-sm-6 col-md-4 first-in-line first-item-of-tablet-line first-item-of-mobile-line hovered']//span[contains(text(),'Add to cart')]\n")
  private WebElement shirtToCart;

  public boolean logOutVisible() {
    return logOutBtn.isEnabled();
  }

  public LoggedPageFactory womenClick() throws Exception {
    women.click();
    return new LoggedPageFactory();
  }

  public void moveMouseToTshirt() throws Exception {
    WebDriver driver = DriverFactory.getDriver();
    JavascriptExecutor js = (JavascriptExecutor) driver;
    js.executeScript("window.scrollBy(0,500)");
    Actions actions = new Actions(driver);
    actions.moveToElement(tShirt).click().perform();
  }
}
