package com.masteringselenium.effectivePageObjects;

import com.masteringselenium.DriverFactory;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.CacheLookup;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.openqa.selenium.support.PageFactory;

/**
 * Package: com.masteringselenium.effectivePageObjects
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 03.01.2019 2019
 */
public class MainPageFactory {
    public MainPageFactory() throws Exception {
        PageFactory.initElements(DriverFactory.getDriver(), this);
    }
    @CacheLookup
    @FindBy(how = How.XPATH, using = "//img[@class='logo img-responsive']")
    private WebElement logo;

    @CacheLookup
    @FindBy(how = How.XPATH, using = "//a[@title='Log in to your customer account']")
    private WebElement login;

    public boolean logoVisible(){
        return logo.isDisplayed();
    }
    public LoginPageFactory loginClick() throws Exception {
        login.click();
        return new LoginPageFactory();
    }
}
