package com.masteringselenium.effectivePageObjects;

import com.masteringselenium.DriverFactory;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.Test;

import static org.testng.Assert.assertTrue;

/**
 * Package: com.masteringselenium.effectivePageObjects Generated by: Hoang.Son.Nguyen Generated at:
 * 03.01.2019 2019
 */
public class MainPageWD extends DriverFactory{
  @Test
  public void checkMainPage() throws Exception {
    WebDriver driver = DriverFactory.getDriver();
    driver.navigate().to("http://automationpractice.com/index.php");
    MainPageFactory mainPageFactory = new MainPageFactory();
    assertTrue(mainPageFactory.logoVisible());
  }
  @Test
  public void checkLoginPage() throws Exception {
    WebDriver driver = DriverFactory.getDriver();
    driver.navigate().to("http://automationpractice.com/index.php");
    MainPageFactory mainPageFactory = new MainPageFactory();
    LoginPageFactory loginPageFactory = mainPageFactory.loginClick();
    assertTrue(loginPageFactory.authenTextDisplay());
    LoggedPageFactory loggedPageFactory = loginPageFactory.susseccLogin();
    loggedPageFactory.logOutVisible();
  }
}
