package com.masteringselenium.config;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

/** Package: config Generated by: Hoang.Son.Nguyen Generated at: 01.01.2019 2019 */
public interface DriverSetup {
  WebDriver getWebDriverObject(DesiredCapabilities desiredCapabilities);

  DesiredCapabilities getDesiredCapabilities();
}
